
inv:	inv.c inv_nla.h inv_arith_algs2.h inv_knuth.h inv_sting.h inv_nec.h inv_allamigeon.h inv_mccune.h inv_lgc.h inv_miscs.h inv_common.h strmap.h 
	gcc inv.c -o inv -lm -gdwarf-2 
clean:	
	rm -rf *.o inv
