
import * as vscode from 'vscode';

export function getAssertionsForLatestVtrace(digOutput: string, currentLineText: string, currentLineIndentation: string): string {
    
    // Extract the vtrace number from the current line
    const vtraceMatch = currentLineText.match(/\bvtrace\w*\s*\(\s*.*\s*\)\s*;/);


    if (!vtraceMatch) {
        vscode.window.showInformationMessage('No vtrace calls on the current line');
        return '';
    }

    // Extract the specific vtrace number, or default to an empty string if unlabeled
    let vtraceNum = vtraceMatch[1] || '';

    // Construct a regex to find the output block related to the specific vtrace call
    let regexPattern = vtraceNum ? `vtrace${vtraceNum}\\w* \\((\\d+) invs\\):([\\s\\S]*?)(?=\\nvtrace\\w* \\(|$)` : `vtrace\\w* \\((\\d+) invs\\):([\\s\\S]*?)(?=\\nvtrace\\w* \\(|$)`;


    let vtracePattern = new RegExp(regexPattern, 'g');
    vtracePattern.lastIndex = 0;
    let vtraceOutputMatch = vtracePattern.exec(digOutput);

    if (vtraceOutputMatch && vtraceOutputMatch[2]) {
        // Split and filter invariants
        let invariants = vtraceOutputMatch[2].trim().split('\n')
            .filter(line => line.match(/^\d+\./));

        // Format the extracted invariants as assertions with added comments that inform the assertions were generated by DIG
        return invariants.map((line, index) => {
            const invariant = line.substring(line.indexOf(' ') + 1);
            const comment = `// DIG generated invariant`;
            const commentIndentation = index === 0 ? '' : currentLineIndentation;
            return `${commentIndentation}${comment}\n${currentLineIndentation}assert(${invariant});`;
        }).join(`\n`);
    }

    // No invariants found for this vtrace call
    return '';
}
