/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 213 "/home/Storage/Src/Software/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/include/stddef.h"
typedef unsigned long size_t;
#line 141 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 142 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 45 "/usr/include/stdio.h"
struct _IO_FILE;
#line 45
struct _IO_FILE;
#line 49 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 170 "/usr/include/libio.h"
struct _IO_FILE;
#line 180 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 186 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 271 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 166 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
#line 353
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 14 "orig.c"
int ALIM(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
         int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
         int Alt_Layer_Value , int Up_Separation , int Down_Separation , int Other_RAC ,
         int Other_Capability , int Climb_Inhibit ) 
{ 


  {
#line 33
  if (Alt_Layer_Value == 0) {
#line 33
    return (400);
  } else
#line 34
  if (Alt_Layer_Value == 1) {
#line 34
    return (500);
  } else
#line 35
  if (Alt_Layer_Value == 2) {
#line 35
    return (640);
  } else {
#line 36
    return (740);
  }
}
}
#line 40 "orig.c"
int Inhibit_Biased_Climb(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
                         int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
                         int Alt_Layer_Value , int Up_Separation , int Down_Separation ,
                         int Other_RAC , int Other_Capability , int Climb_Inhibit ) 
{ 
  int tmp ;

  {
#line 54
  if (Climb_Inhibit) {
#line 54
    tmp = 100 + Up_Separation;
  } else {
#line 54
    tmp = Up_Separation;
  }
#line 54
  return (tmp);
}
}
#line 91
int Own_Below_Threat(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
                     int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
                     int Alt_Layer_Value , int Up_Separation , int Down_Separation ,
                     int Other_RAC , int Other_Capability , int Climb_Inhibit ) ;
#line 128
int Own_Above_Threat(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
                     int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
                     int Alt_Layer_Value , int Up_Separation , int Down_Separation ,
                     int Other_RAC , int Other_Capability , int Climb_Inhibit ) ;
#line 60 "orig.c"
int Non_Crossing_Biased_Climb(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
                              int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
                              int Alt_Layer_Value , int Up_Separation , int Down_Separation ,
                              int Other_RAC , int Other_Capability , int Climb_Inhibit ) 
{ 
  int upward_preferred ;
  int result ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;

  {
#line 77
  tmp = Inhibit_Biased_Climb(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                             Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                             Alt_Layer_Value, Up_Separation, Down_Separation, Other_RAC,
                             Other_Capability, Climb_Inhibit);
#line 77
  upward_preferred = tmp > Down_Separation;
#line 89
  if (upward_preferred) {
#line 91
    tmp___0 = Own_Below_Threat(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                               Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                               Alt_Layer_Value, Up_Separation, Down_Separation, Other_RAC,
                               Other_Capability, Climb_Inhibit);
#line 91
    if (tmp___0) {
#line 91
      tmp___1 = Own_Below_Threat(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                                 Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                                 Alt_Layer_Value, Up_Separation, Down_Separation,
                                 Other_RAC, Other_Capability, Climb_Inhibit);
#line 91
      if (tmp___1) {
#line 91
        tmp___2 = ALIM(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                       Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt, Alt_Layer_Value,
                       Up_Separation, Down_Separation, Other_RAC, Other_Capability,
                       Climb_Inhibit);
#line 91
        if (Down_Separation >= tmp___2) {
#line 91
          tmp___3 = 0;
        } else {
#line 91
          tmp___3 = 1;
        }
      } else {
#line 91
        tmp___3 = 0;
      }
    } else {
#line 91
      tmp___3 = 1;
    }
#line 91
    result = tmp___3;
  } else {
#line 128
    tmp___4 = Own_Above_Threat(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                               Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                               Alt_Layer_Value, Up_Separation, Down_Separation, Other_RAC,
                               Other_Capability, Climb_Inhibit);
#line 128
    if (tmp___4) {
#line 128
      if (Cur_Vertical_Sep >= 300) {
#line 128
        tmp___5 = ALIM(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                       Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt, Alt_Layer_Value,
                       Up_Separation, Down_Separation, Other_RAC, Other_Capability,
                       Climb_Inhibit);
#line 128
        if (Up_Separation >= tmp___5) {
#line 128
          tmp___6 = 1;
        } else {
#line 128
          tmp___6 = 0;
        }
      } else {
#line 128
        tmp___6 = 0;
      }
    } else {
#line 128
      tmp___6 = 0;
    }
#line 128
    result = tmp___6;
  }
#line 152
  return (result);
}
}
#line 155 "orig.c"
int Non_Crossing_Biased_Descend(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
                                int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
                                int Alt_Layer_Value , int Up_Separation , int Down_Separation ,
                                int Other_RAC , int Other_Capability , int Climb_Inhibit ) 
{ 
  int upward_preferred ;
  int result ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;

  {
#line 172
  tmp = Inhibit_Biased_Climb(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                             Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                             Alt_Layer_Value, Up_Separation, Down_Separation, Other_RAC,
                             Other_Capability, Climb_Inhibit);
#line 172
  upward_preferred = tmp > Down_Separation;
#line 184
  if (upward_preferred) {
#line 186
    tmp___0 = Own_Below_Threat(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                               Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                               Alt_Layer_Value, Up_Separation, Down_Separation, Other_RAC,
                               Other_Capability, Climb_Inhibit);
#line 186
    if (tmp___0) {
#line 186
      if (Cur_Vertical_Sep >= 300) {
#line 186
        tmp___1 = ALIM(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                       Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt, Alt_Layer_Value,
                       Up_Separation, Down_Separation, Other_RAC, Other_Capability,
                       Climb_Inhibit);
#line 186
        if (Down_Separation >= tmp___1) {
#line 186
          tmp___2 = 1;
        } else {
#line 186
          tmp___2 = 0;
        }
      } else {
#line 186
        tmp___2 = 0;
      }
    } else {
#line 186
      tmp___2 = 0;
    }
#line 186
    result = tmp___2;
  } else {
#line 212
    tmp___3 = Own_Above_Threat(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                               Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                               Alt_Layer_Value, Up_Separation, Down_Separation, Other_RAC,
                               Other_Capability, Climb_Inhibit);
#line 212
    if (tmp___3) {
#line 212
      tmp___4 = Own_Above_Threat(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                                 Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                                 Alt_Layer_Value, Up_Separation, Down_Separation,
                                 Other_RAC, Other_Capability, Climb_Inhibit);
#line 212
      if (tmp___4) {
#line 212
        tmp___5 = ALIM(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                       Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt, Alt_Layer_Value,
                       Up_Separation, Down_Separation, Other_RAC, Other_Capability,
                       Climb_Inhibit);
#line 212
        if (Up_Separation >= tmp___5) {
#line 212
          tmp___6 = 1;
        } else {
#line 212
          tmp___6 = 0;
        }
      } else {
#line 212
        tmp___6 = 0;
      }
    } else {
#line 212
      tmp___6 = 1;
    }
#line 212
    result = tmp___6;
  }
#line 247
  return (result);
}
}
#line 250 "orig.c"
int Own_Below_Threat(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
                     int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
                     int Alt_Layer_Value , int Up_Separation , int Down_Separation ,
                     int Other_RAC , int Other_Capability , int Climb_Inhibit ) 
{ 


  {
#line 263
  return (Own_Tracked_Alt < Other_Tracked_Alt);
}
}
#line 266 "orig.c"
int Own_Above_Threat(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
                     int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
                     int Alt_Layer_Value , int Up_Separation , int Down_Separation ,
                     int Other_RAC , int Other_Capability , int Climb_Inhibit ) 
{ 


  {
#line 279
  return (Other_Tracked_Alt < Own_Tracked_Alt);
}
}
#line 282 "orig.c"
int alt_sep_test(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
                 int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
                 int Alt_Layer_Value , int Up_Separation , int Down_Separation , int Other_RAC ,
                 int Other_Capability , int Climb_Inhibit ) 
{ 
  int enabled ;
  int tcas_equipped ;
  int intent_not_known ;
  int need_upward_RA ;
  int need_downward_RA ;
  int alt_sep ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;

  {
#line 299
  if (High_Confidence) {
#line 299
    if (Own_Tracked_Alt_Rate <= 600) {
#line 299
      if (Cur_Vertical_Sep > 600) {
#line 299
        tmp = 1;
      } else {
#line 299
        tmp = 0;
      }
    } else {
#line 299
      tmp = 0;
    }
  } else {
#line 299
    tmp = 0;
  }
#line 299
  enabled = tmp;
#line 300
  tcas_equipped = Other_Capability == 1;
#line 301
  if (Two_of_Three_Reports_Valid) {
#line 301
    if (Other_RAC == 0) {
#line 301
      tmp___0 = 1;
    } else {
#line 301
      tmp___0 = 0;
    }
  } else {
#line 301
    tmp___0 = 0;
  }
#line 301
  intent_not_known = tmp___0;
#line 303
  alt_sep = 0;
#line 305
  if (enabled) {
#line 305
    if (tcas_equipped) {
#line 305
      if (intent_not_known) {
#line 305
        goto _L___0;
      } else {
#line 305
        goto _L___1;
      }
    } else
    _L___1: /* CIL Label */ 
#line 305
    if (! tcas_equipped) {
      _L___0: /* CIL Label */ 
#line 307
      tmp___1 = Non_Crossing_Biased_Climb(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                                          Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                                          Alt_Layer_Value, Up_Separation, Down_Separation,
                                          Other_RAC, Other_Capability, Climb_Inhibit);
#line 307
      if (tmp___1) {
#line 307
        tmp___2 = Own_Below_Threat(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                                   Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                                   Alt_Layer_Value, Up_Separation, Down_Separation,
                                   Other_RAC, Other_Capability, Climb_Inhibit);
#line 307
        if (tmp___2) {
#line 307
          tmp___3 = 1;
        } else {
#line 307
          tmp___3 = 0;
        }
      } else {
#line 307
        tmp___3 = 0;
      }
#line 307
      need_upward_RA = tmp___3;
#line 331
      tmp___4 = Non_Crossing_Biased_Descend(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                                            Own_Tracked_Alt, Own_Tracked_Alt_Rate,
                                            Other_Tracked_Alt, Alt_Layer_Value, Up_Separation,
                                            Down_Separation, Other_RAC, Other_Capability,
                                            Climb_Inhibit);
#line 331
      if (tmp___4) {
#line 331
        tmp___5 = Own_Above_Threat(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                                   Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt,
                                   Alt_Layer_Value, Up_Separation, Down_Separation,
                                   Other_RAC, Other_Capability, Climb_Inhibit);
#line 331
        if (tmp___5) {
#line 331
          tmp___6 = 1;
        } else {
#line 331
          tmp___6 = 0;
        }
      } else {
#line 331
        tmp___6 = 0;
      }
#line 331
      need_downward_RA = tmp___6;
#line 354
      if (need_upward_RA) {
#line 354
        if (need_downward_RA) {
#line 358
          alt_sep = 0;
        } else {
#line 354
          goto _L;
        }
      } else
      _L: /* CIL Label */ 
#line 359
      if (need_upward_RA) {
#line 360
        alt_sep = 1;
      } else
#line 361
      if (need_downward_RA) {
#line 362
        alt_sep = 2;
      } else {
#line 364
        alt_sep = 0;
      }
    }
  }
#line 367
  return (alt_sep);
}
}
#line 375 "orig.c"
int mainQ(int Cur_Vertical_Sep , int High_Confidence , int Two_of_Three_Reports_Valid ,
          int Own_Tracked_Alt , int Own_Tracked_Alt_Rate , int Other_Tracked_Alt ,
          int Alt_Layer_Value , int Up_Separation , int Down_Separation , int Other_RAC ,
          int Other_Capability , int Climb_Inhibit ) 
{ 
  int tmp ;

  {
#line 387
  tmp = alt_sep_test(Cur_Vertical_Sep, High_Confidence, Two_of_Three_Reports_Valid,
                     Own_Tracked_Alt, Own_Tracked_Alt_Rate, Other_Tracked_Alt, Alt_Layer_Value,
                     Up_Separation, Down_Separation, Other_RAC, Other_Capability,
                     Climb_Inhibit);
#line 387
  return (tmp);
}
}
#line 403
extern int ( /* missing proto */  atoi)() ;
#line 401 "orig.c"
int main(int argc , char **argv ) 
{ 
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int tmp___11 ;

  {
#line 403
  tmp = atoi(*(argv + 12));
#line 403
  tmp___0 = atoi(*(argv + 11));
#line 403
  tmp___1 = atoi(*(argv + 10));
#line 403
  tmp___2 = atoi(*(argv + 9));
#line 403
  tmp___3 = atoi(*(argv + 8));
#line 403
  tmp___4 = atoi(*(argv + 7));
#line 403
  tmp___5 = atoi(*(argv + 6));
#line 403
  tmp___6 = atoi(*(argv + 5));
#line 403
  tmp___7 = atoi(*(argv + 4));
#line 403
  tmp___8 = atoi(*(argv + 3));
#line 403
  tmp___9 = atoi(*(argv + 2));
#line 403
  tmp___10 = atoi(*(argv + 1));
#line 403
  tmp___11 = mainQ(tmp___10, tmp___9, tmp___8, tmp___7, tmp___6, tmp___5, tmp___4,
                   tmp___3, tmp___2, tmp___1, tmp___0, tmp);
#line 403
  fprintf((FILE * __restrict  )stdout, (char const   * __restrict  )"%d\n", tmp___11);
#line 416
  return (0);
}
}
