import * as vscode from 'vscode';
import { exec } from 'child_process';
import { getAssertionsForLatestVtrace } from '../utils/dig_utils';
import * as path from 'path';

/**
 * Inserts generated assertions from DIG into the currently active text editor.
 */
export function insertAssertions() {
    // Get the active text editor where the command was invoked
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
        // If no editor is active, display a message to the user
        vscode.window.showInformationMessage('Open a file to insert assertions.');
        return;
    }

    // Capture the indentation and the cursor position before starting the async operation
    const initialPosition = editor.selection.active;
    const currentLine = editor.document.lineAt(initialPosition.line);
    const currentLineIndentation = currentLine.text.substring(0, currentLine.firstNonWhitespaceCharacterIndex);

     // Extract the file path and filename of the current document
    const filePath = editor.document.uri.fsPath;
    const filename = path.basename(filePath);

    //--platform linux/amd64

    // Construct the command to run DIG within a Docker container
    const dockerCommand = `docker run -v "${filePath}:/dig/src/${filename}" -w /dig/src dig /bin/bash -c "/root/miniconda3/bin/python3 -O dig.py ${filename} -log 4"`;
    console.log("Running command:", dockerCommand);
    
    // Display a progress notification while DIG is running
    vscode.window.withProgress({
        location: vscode.ProgressLocation.Notification,
        title: "Running DIG",
        cancellable: false
    }, (progress, token) => {
        // Execute the DIG command
        return new Promise<void>((resolve, reject) => {
            exec(dockerCommand, (error, stdout, stderr) => {
                // Log the standard output for debugging purposes
                console.log(`STDOUT: ${stdout}`);
                
                if (error) {
                    // If there's an error, display it to the user and log it
                    vscode.window.showErrorMessage(`Error running DIG: ${stderr}`);
                    console.error(`Execution Error: ${error}`);
                    return reject();
                }

                // Process and log any standard error output
                if (stderr.trim()) {
                    console.error(`STDERR: ${stderr}`);
                }

                // Handle the case where DIG does not generate any invariants
                if (!stdout.trim()) {
                    vscode.window.showInformationMessage('No invariants generated by DIG.');
                    return resolve();
                }


                // Extract the generated invariants from DIG's output
                const lines = stdout.split('\n');
                const invariantLines = lines.filter(line => line.match(/^\d+\./));


                 // Format the extracted invariants as assertions with the correct indentation
                const assertions = invariantLines.map(line => {
                    const invariant = line.substring(line.indexOf(' ') + 1);
                    return `${currentLineIndentation}assert(${invariant});`;
                }).join('\n');
                
                // Insert the formatted assertions into the document
                if (!assertions) {
                    vscode.window.showInformationMessage('No invariants generated by DIG.');
                    return resolve();
                }

                //const position = editor.selection.active;
                const textUpToPosition = editor.document.getText(new vscode.Range(new vscode.Position(0,0), initialPosition));
                const formattedAssertions = getAssertionsForLatestVtrace(stdout, textUpToPosition, currentLineIndentation);

                editor.edit(editBuilder => {
                    //editBuilder.insert(initialPosition, `\n\n${assertions}\n`);
                    editBuilder.insert(initialPosition, `\n${currentLineIndentation}${formattedAssertions}\n`);
                }).then(() => resolve()); // Ensure the progress notification is closed
            });

                // Handle cancellation by the user
                token.onCancellationRequested(() => {
                    console.log("User canceled the running operation");
                    reject();
                });
            });
        });
}



