

import * as vscode from 'vscode';
import { exec } from 'child_process';
import { getAssertionsForLatestVtrace} from '../utils/dig_utils';
import * as path from 'path';

/**
 * Inserts generated assertions from DIG into the currently active text editor.
 */
export function insertAssertions() {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
        vscode.window.showInformationMessage('Open a file to insert assertions.');
        return;
    }

    const currentPosition = editor.selection.active;
    const currentLine = editor.document.lineAt(currentPosition.line);
    const currentLineIndentation = currentLine.text.substring(0, currentLine.firstNonWhitespaceCharacterIndex);

    // Check if the current line contains a vtrace() call
    const currentLineText = currentLine.text.trim();
    const vtraceMatch = currentLineText.match(/\bvtrace\w*\s*\(.*\)\s*;/);

    if (!vtraceMatch) {
        vscode.window.showInformationMessage('No vtrace call found on the current line');
        return;
    }

    const filePath = editor.document.uri.fsPath;
    const filename = path.basename(filePath);

    // Command to start a Docker container
    const dockerStartCommand = `docker run -d --platform linux/amd64 -v "${filePath}:/dig/src/${filename}" -w /dig/src dig tail -f /dev/null`;
    console.log("Starting Docker container:", dockerStartCommand);

    // Display progress notification while DIG is running
    vscode.window.withProgress({
        location: vscode.ProgressLocation.Notification,
        title: "Running DIG",
        cancellable: false
    }, (progress, token) => {
        return new Promise<void>((resolve, reject) => {
            exec(dockerStartCommand, (error, stdout, stderr) => {
                if (error) {
                    vscode.window.showErrorMessage(`Error starting Docker container: ${stderr}`);
                    console.error(`Start Error: ${error}`);
                    return reject();
                }

                const containerId = stdout.trim();
                console.log(`Docker container started with ID: ${containerId}`);

                const runScriptCommand = `docker exec ${containerId} /root/miniconda3/bin/python3 -O dig.py ${filename} -log 2`;
                console.log("Running script inside Docker container:", runScriptCommand);

                exec(runScriptCommand, (error, stdout, stderr) => {
                    console.log(`STDOUT: ${stdout}`);
                    if (error) {
                        vscode.window.showErrorMessage(`Error running DIG: ${stderr}`);
                        console.error(`Execution Error: ${error}`);
                        return reject();
                    }

                    if (stderr.trim()) {
                        console.error(`STDERR: ${stderr}`);
                    }

                    if (!stdout.trim()) {
                        vscode.window.showInformationMessage('No invariants generated by DIG.');
                        return resolve();
                    }

                     // Extract and format the generated invariants
                    const lines = stdout.split('\n');
                    const invariantLines = lines.filter(line => line.match(/^\d+\.\s+/));

                    const assertions = invariantLines.map(line => {
                        const invariant = line.substring(line.indexOf(' ') + 1).trim();
                        return `${currentLineIndentation}assert(${invariant});`;
                    }).join('\n');

                    if (!assertions) {
                        vscode.window.showInformationMessage('No invariants generated by DIG.');
                        return resolve();
                    }

                    const initialPosition = currentPosition;
                    const textUpToPosition = editor.document.getText(new vscode.Range(new vscode.Position(0, 0), initialPosition));
                    const formattedAssertions = getAssertionsForLatestVtrace(stdout, textUpToPosition, currentLineIndentation);
                    const insertPosition = new vscode.Position(initialPosition.line + 1, 0);

                     // Insert the assertions into the document
                    editor.edit(editBuilder => {
                        editBuilder.insert(insertPosition, `\n${currentLineIndentation}${formattedAssertions}\n`);
                    }).then(() => resolve());

                    // Command to stop and remove the Docker container
                    const stopContainerCommand = `docker stop ${containerId} && docker rm ${containerId}`;
                    console.log("Stopping and removing Docker container:", stopContainerCommand);
                    exec(stopContainerCommand, (error, stdout, stderr) => {
                        if (error) {
                            console.error(`Stop Error: ${error}`);
                        }
                    });
                });

                // Handle cancellation by the user
                token.onCancellationRequested(() => {
                    console.log("User canceled the running operation");
                    const stopContainerCommand = `docker stop ${containerId} && docker rm ${containerId}`;
                    exec(stopContainerCommand, (error, stdout, stderr) => {
                        if (error) {
                            console.error(`Stop Error: ${error}`);
                        }
                    });
                    reject();
                });
            });
        });
    });
}
