


clean:
	rm -rf *.pyo *.pyc *~
	rm -rf data/*.pyo data/*.pyc data/*~
	rm -rf data/invs/*.pyo data/invs/*.pyc data/invs/*~
	rm -rf data/poly/*.pyo data/poly/*.pyc data/poly/*~
	rm -rf cegir/*.pyo cegir/*.pyc cegir/*~
