str: infer_axioms.py JString.py
	sage infer_axioms.py JString.py
ll: infer_axioms.py JLinkedList.py
	sage infer_axioms.py JLinkedList.py
stack: infer_axioms.py JStack.py
	sage infer_axioms.py JStack.py
	